// List of engineering subjects
export const Subjects = [
        { label: 'Mathematics', year: 1 },
        { label: 'Physics', year: 1 },
        { label: 'Chemistry', year: 1 },
        { label: 'Computer Programming', year: 1 },
        { label: 'Electrical Engineering', year: 2 },
        { label: 'Mechanical Engineering', year: 2 },
        { label: 'Civil Engineering', year: 2 },
        { label: 'Electronics Engineering', year: 2 },
        { label: 'Data Structures and Algorithms', year: 3 },
        { label: 'Database Management Systems', year: 3 },
        { label: 'Operating Systems', year: 3 },
        { label: 'Software Engineering', year: 3 },
        { label: 'Networks and Communications', year: 4 },
        { label: 'Artificial Intelligence', year: 4 },
        { label: 'Machine Learning', year: 4 },
        { label: 'Web Development', year: 4 },
        { label: 'Control Systems', year: 5 },
        { label: 'Power Systems', year: 5 },
        { label: 'Digital Signal Processing', year: 5 },
        { label: 'VLSI Design', year: 5 },
        { label: 'Robotics', year: 6 },
        { label: 'Embedded Systems', year: 6 },
        { label: 'Internet of Things', year: 6 },
        { label: 'Cybersecurity', year: 6 },
        { label: 'Project Management', year: 7 },
        { label: 'Entrepreneurship', year: 7 },
        { label: 'Ethics in Engineering', year: 7 },
        { label: 'Technical Writing', year: 7 },
        { label: 'Renewable Energy Systems', year: 8 },
        { label: 'Sustainable Design', year: 8 },
        { label: 'Green Building Technologies', year: 8 },
        { label: 'Engineering Economics', year: 8 },
        { label: 'Quality Control', year: 9 },
        { label: 'Operations Research', year: 9 },
        { label: 'Supply Chain Management', year: 9 },
        { label: 'Lean Manufacturing', year: 9 },
        { label: 'Biomedical Engineering', year: 10 },
        { label: 'Bioinformatics', year: 10 },
        { label: 'Nanotechnology', year: 10 },
        { label: 'Renewable Energy Engineering', year: 10 },
        { label: 'Aerospace Engineering', year: 11 },
        { label: 'Automotive Engineering', year: 11 },
        { label: 'Marine Engineering', year: 11 },
        { label: 'Petroleum Engineering', year: 11 },
        { label: 'Civil Infrastructure Engineering', year: 12 },
        { label: 'Geotechnical Engineering', year: 12 },
        { label: 'Structural Engineering', year: 12 },
        { label: 'Transportation Engineering', year: 12 },
        { label: 'Chemical Engineering', year: 13 },
        { label: 'Biotechnology', year: 13 },
        { label: 'Food Engineering', year: 13 },
        { label: 'Environmental Engineering', year: 13 },
        { label: 'Materials Science and Engineering', year: 14 },
        { label: 'Metallurgical Engineering', year: 14 },
        { label: 'Polymer Engineering', year: 14 },
        { label: 'Ceramic Engineering', year: 14 },
        { label: 'Industrial Engineering', year: 15 },
        { label: 'Manufacturing Engineering', year: 15 },
        { label: 'Operations Management', year: 15 },
        { label: 'Supply Chain Engineering', year: 15 },
        { label: 'Mechatronics Engineering', year: 16 },
        { label: 'Robotics Engineering', year: 16 },
        { label: 'Control Engineering', year: 16 },
        { label: 'Artificial Intelligence Engineering', year: 16 },
        { label: 'Software Engineering', year: 17 },
        { label: 'Web Development', year: 17 },
        { label: 'Mobile App Development', year: 17 },
        { label: 'Cloud Computing', year: 17 },
        { label: 'Data Science', year: 18 },
        { label: 'Machine Learning', year: 18 },
        { label: 'Big Data Analytics', year: 18 },
        { label: 'Data Visualization', year: 18 },
        { label: 'Cybersecurity', year: 19 },
        { label: 'Network Security', year: 19 },
        { label: 'Ethical Hacking', year: 19 },
        { label: 'Digital Forensics', year: 19 },
        { label: 'Project Management', year: 20 },
        { label: 'Agile Methodology', year: 20 },
        { label: 'Scrum', year: 20 },
        { label: 'Kanban', year: 20 },
    ];
